### ISSUE TITLE
First sample failed.

### ISSUE THREAD

**Issue by tama1029** [cardmagic/simple-rss#24]
This url contains a redirect loop.

`rss = SimpleRSS.parse open('http://slashdot.org/index.rdf')`

I want to change the url after redirect.

**Comment by tama1029** [comment]
https://github.com/cardmagic/simple-rss#usage

I use this sample.

result

```text
/Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:224:in `open_loop': redirection forbidden: http://slashdot.org/index.rdf -> https://slashdot.org/index.rdf (RuntimeError)
	from /Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
	from /Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:716:in `open'
	from /Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:34:in `open'
	from parse_test.rb:5:in `<main>'
```
