### ISSUE TITLE
private method `link' called for #<SimpleRSS:0x9aaf59c> in ruby 1.9.2

### ISSUE THREAD

**Issue by murugaraj** [cardmagic/simple-rss#6]
In ruby 1.9.2 Calling rss.channel.link or rss.channel.title throwing the below error.

Please Fix.

ruby-1.9.2-p0 >   rss.channel.link
NoMethodError: private method `link' called for #<SimpleRSS:0x9aaf59c>
    from (irb):29
    from /home/dckap/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.0/lib/rails/commands/console.rb:44:in`start'
    from /home/dckap/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.0/lib/rails/commands/console.rb:8:in `start'
    from /home/dckap/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.0/lib/rails/commands.rb:23:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'
ruby-1.9.2-p0 > rss.channel.title
NoMethodError: private method `title' called for #<SimpleRSS:0x9aaf59c>
    from (irb):30
    from /home/dckap/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.0/lib/rails/commands/console.rb:44:in`start'
    from /home/dckap/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.0/lib/rails/commands/console.rb:8:in `start'
    from /home/dckap/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.0/lib/rails/commands.rb:23:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by cardmagic** [comment]
This was fixed in commit 4094322. The dynamically created accessor methods are now public. Verified working in Ruby 3.4.
